function Hd = HW3_FIR
%HW3_FIR Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.13 and Signal Processing Toolbox 9.1.
% Generated on: 08-Apr-2025 22:51:17

% Equiripple Bandpass filter designed using the FIRPM function.

% All frequency values are normalized to 1.

Fstop1 = 0.1;             % First Stopband Frequency
Fpass1 = 0.15;            % First Passband Frequency
Fpass2 = 0.25;            % Second Passband Frequency
Fstop2 = 0.3;             % Second Stopband Frequency
Dstop1 = 0.001;           % First Stopband Attenuation
Dpass  = 0.057501127785;  % Passband Ripple
Dstop2 = 0.001;           % Second Stopband Attenuation
dens   = 20;              % Density Factor

% Calculate the order from the parameters using FIRPMORD.
[N, Fo, Ao, W] = firpmord([Fstop1 Fpass1 Fpass2 Fstop2], [0 1 0], ...
                          [Dstop1 Dpass Dstop2]);

% Calculate the coefficients using the FIRPM function.
b  = firpm(N, Fo, Ao, W, {dens});
Hd = dfilt.dffir(b);

% [EOF]
